# Candlestick constants
CANDLESTICK_DATETIME_OPEN = "DATETIME_OPEN"
CANDLESTICK_DATETIME_CLOSE = "DATETIME_CLOSE"
CANDLESTICK_OPEN = "OPEN_POINTS"
CANDLESTICK_HIGH = "HIGH_POINTS"
CANDLESTICK_LOW = "LOW_PONTS"
CANDLESTICK_CLOSE = "CLOSE_POINTS"
CANDLESTICK_VOLUME = "VOLUME_POJNTS"